### ISSUE TITLE
[KDE/Wayland/fcitx5] Emoji picker appears and then vanishes immediately

### ISSUE THREAD

**Issue by milas** [GaZaTu/im-emoji-picker#13]
Splitting this out from the conversation in #11:

 > ok the only thing i can imagine at this point is that there must be some kind of bug with KDE (wayland) + fcitx5 because fcitx immediately sends the `deactivate` event after the window opens (which is obviously wrong) and then it goes dark.
> if i start the fcitx daemon with `QT_QPA_PLATFORM=xcb` it kinda works but that's obviously no solution.

_Originally posted by @GaZaTu in https://github.com/GaZaTu/im-emoji-picker/issues/11#issuecomment-1657235748_

I filed an upstream issue with @ fcitx/fcitx5#887, and the maintainer responded:
> That's however, not a solvable issue from fcitx side.
>
> Mainly it's because that the emoji picker itself embeds Qt and it will grab the focus away on wayland. that's why you see the deactivate event.

---

At this point, it's not clear to me where the issue lies - is this a kwin thing? Why do we not see the same behavior under X11?

For reference, here's my system configuration:
```
KWin version: 5.27.9
Qt Version: 5.15.10
Qt compile version: 5.15.10
XCB compile version: 1.16

fcitx version: 5.1.1
Kernel: 6.5.9
```
I also tried using latest `HEAD` from both fcitx + im-emoji-picker.

**Comment by GaZaTu** [comment]
im wasted af rn but i know the issue: under @milas wayland qt always steals
focus which is bad in this case. if u want to use this prohect youll need
to create a window rule to disable focus for now

**Comment by shadmansaleh** [comment]
Any update on this? I think I'm facing same issue with ibus-wayland on kde too.

**Comment by GaZaTu** [comment]
@shadmansaleh i did not look into this again but i doubt anything changed yet. There currently does not seem to be a way to tell Qt "open a new window but do not take focus" when using wayland.

So the only way for now seems to be a custom window rule in the KDE settings. (which is what i did)

**Comment by milas** [comment]
For reference, here's what my `~/.config/kwinrulesrc` looks like:
```ini
[1]
Description=Emoji Picker
acceptfocusrule=2
title=im-emoji-picker
titlematch=2
types=1

[General]
count=1
rules=1
```

Configuring it in the GUI:
![Screenshot of the KDE Window Rules configuration pane with a rule targeting window title of "im-emoji-picker" and setting "Accept Focus" to "Force" and "No"](https://github.com/GaZaTu/im-emoji-picker/assets/841263/b4f0b61a-29db-4700-aecd-9c5a136c0ae5)

---

Things are working well for me since applying that change on KDE 5.27.10 + Wayland (on NixOS unstable) using fcitx5.

Thanks for this, it's pretty great. Maybe Qt6 will fix things? 🫣 <-- emoji typed with `im-emoji-picker`

**Comment by milas** [comment]
btw I had to launch Firefox under xwayland to respond to this issue. This issue literally breaks input on Firefox+Wayland for me. Specifically _this_ issue. I can comment on **other** GitHub issues but not this one.

(This has nothing to do with `im-emoji-picker`. It happens even without fcitx5 running. I have no explanation and don't even know how to report that as a bug to Firefox, so I felt like sharing here 😛)

**Comment by GaZaTu** [comment]
lol that is oddly specific. i did not have that happen before but i guess i don't comment on too many issues. and glad you're still enjoying the emoji picker 😙

**Comment by zelch** [comment]
@GaZaTu Sorry to resurrect a dead bug, but could we get a note about this in the README?

I spent some time trying to figure it out before stumbling across this closed bug.

**Comment by GaZaTu** [comment]
done @zelch 👌

**Comment by GaZaTu** [comment]
@joaociocca I don't think i can help you because vivaldi works for me. 
![Screenshot_20241121_194028](https://github.com/user-attachments/assets/5eff9dd3-832a-4a3c-88ce-019539b38797)

**Comment by joaociocca** [comment]
thanks for trying <3 I really have no idea why it won't work here... 
From Telegram, it works just fine - both the popup showing as the popup filling the chosen emojis
![image](https://github.com/user-attachments/assets/42624a07-e9d9-45d8-9325-00798edb9ed8)

But on Vivaldi, the popup won't even show up =(

**Comment by TechniKris** [comment]
> Configuring it in the GUI: ![Screenshot of the KDE Window Rules configuration pane with a rule targeting window title of "im-emoji-picker" and setting "Accept Focus" to "Force" and "No"](https://github.com/GaZaTu/im-emoji-picker/assets/841263/b4f0b61a-29db-4700-aecd-9c5a136c0ae5)

As of Plasma 6.5.0 the emoji picker appears below the current window. Now it also requires a property:
**"Layer" → "Force" → "Popup"**. 

"Above" would've been enough to display above generic windows, but "Popup" level allows it to appear on top of fullscreen things, like games.
<img width="1060" height="808" alt="Image" src="https://github.com/user-attachments/assets/a569521c-bc36-4199-a857-69dd277e5451" />

I feel like at this point it'd be beneficial to, if possible, bundle a config file for KWin with im-emoji-picker, which would set the appropriate window rules.
