### ISSUE TITLE
How can i get emoji popup while typing with specific string

### ISSUE THREAD

**Issue by niksingh710** [GaZaTu/im-emoji-picker#14]
like `:smiley` then getting the emoji popup showing with the typed string?

**Comment by GaZaTu** [comment]
I'm sorry but the emoji picker was not designed in a way to replace existing text (for example your `:smiley`).
You must open the emoji picker beforehand.

This could be added as a new feature i think but idk i'm kinda lazy.

**Comment by niksingh710** [comment]
> I'm sorry but the emoji picker was not designed in a way to replace existing text (for example your `:smiley`). You must open the emoji picker beforehand.
> 
> This could be added as a new feature i think but idk i'm kinda lazy.

Understandable ..... np as this much it works fine and gets the job done.
This maybe in the docs, but is there anyway to give font explicitly?

**Comment by GaZaTu** [comment]
No there is not, but that is easy enough to fix. I'll add that later today.

**Comment by schrmh** [comment]
@niksingh710 espanso can do actions on typed text. It may be possible to let it trigger im-emoji-picker somehow.
Not sure if it could then also call e.g. xdotool but in worst case add devilspie2 to detect the window and some complex script that then calls xdotool...
