### ISSUE TITLE
Picker not showing up on Krita 5.2.3 (Rich) Text input window

### ISSUE THREAD

**Issue by schrmh** [GaZaTu/im-emoji-picker#17]
The affected window shows up when using the Text creation tool that is at the very top in the left toolbar. (In contrast to other text creation tools, Krita's one expects click and drag on the canvas instead of a simple click)

Still on X11 of course... I think that version of Krita still uses Qt5 but they are definitely in the process of porting to Qt6.
I just use Krita from standard Arch repos.

xprop info of the affected window:
[krita_xprop.txt](https://github.com/user-attachments/files/16476973/krita_xprop.txt)

**Comment by GaZaTu** [comment]
I'm not sure I understand what the issue is. Need more information or a screenshot.

**Comment by schrmh** [comment]
![image](https://github.com/user-attachments/assets/ddc209cc-26ce-4780-8197-33deb5344a9a)
The issue is that the im-emoji-picker window doesn't appear when I want to insert an emoji in this window (which is possible as you can see; manually copy and pasted the emoji from clipboard) after pressing Ctrl + Alt + . (my shortcut for the emoji picker window) while it just works everywhere else.

**Comment by schrmh** [comment]
Turns out that the global vars for fcitx5 weren't set anymore. Guess I deleted them by accident when I moved around some config stuff.
Well.
