### ISSUE TITLE
Add config key for QoL

### ISSUE THREAD

**Issue by ahmubashshir** [GaZaTu/im-emoji-picker#8]
Current behavior is `<Tab>`/`<Shift><Tab>` changes page and `<Left>`/`<Right>` changes suggestion.

I'd like to assign `[`/`]` for changing page and `,`/`.` to change suggestion. I'd be happy if you implement this, or direct me to where this is handled, I'll try implementing myself.

Another suggestion is allowing users to merge 3 pages into one with a config key.

**Comment by GaZaTu** [comment]
@ahmubashshir you can try out #9

you just need to add the following snippet to `~/.config/gazatu.xyz/im-emoji-picker.ini`
```ini
[customHotKeys]
1\sourceKeyChr=, 
1\targetKeySeq=Left
2\sourceKeyChr=.
2\targetKeySeq=Right
3\sourceKeyChr=[
3\targetKeySeq=Tab
4\sourceKeyChr=]
4\targetKeySeq=Shift+Tab
size=4
```
